[package]
name = "tl"
version = "0.1.0"
authors = ["Jesse Jaggars <jhjaggars@gmail.com>"]

[dependencies]
clap = "2.32.0"
chrono = { version = "0.4.5", features = ["serde"] }
chrono-humanize = "0.0.11"
colored = "*"
dirs = "1.0"
rand = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
